### ISSUE TITLE
request a mudule

### ISSUE THREAD

**Issue by timieazy** [ElitecloudevOpsroom/terraform-course#1]
tried this but  not working still gave it a path but fail still

module "ec2_instance" {

    source            = "???"
    availability_zone = var.availability_zone
 
![mudule issue](https://user-images.githubusercontent.com/65261675/142509403-4813f31e-083f-46d8-accf-2422c4d563c3.png)
 }

**Comment by ArerepadeBenagha** [comment]
Source should be among the meta data to create and instance.
Refactor that.
